### ISSUE TITLE
How to do works in Heroku?

### ISSUE THREAD

**Issue by danielmeloalencar** [jayu/tcp-local-tunnel#9]

**Comment by jayu** [comment]
I'm afraid you cannot make it work with Heroku. Heroku does not give direct access to ports on a machine, instead, you have to start the app on be port provided by Heroku in env var. 
In order to make this module work on a server, you need to have access to at least two ports exposed to the outside word.
On Heroku, your app is kind of working internally in their infra, and traffic is proxied to the app instance, but you cannot say that your app should have open port X on the Heroku server.
